### ISSUE TITLE
Make property proposal for "relates to SDG number"

### ISSUE THREAD

**Issue by Ainali** [Ainali/ideas#48]
During the follow-up from Wikimania in Daniel-Mietchen/ideas#1480 we got the idea of making a new property. This because it is very expensive to try to traverse properties to get to the SDG's in other ways, and thus such queries usually timeout.

**Comment by Ainali** [comment]
The question is, should this be for main SDG or for the target? 

I was first thinking that it should be for the SDG, qualified with the target. But that would kind of redundant as the SDG would be implied by the target, meaning that if you add the target, the SDG can easily be deduced. 

However, just using SDG and not requiring qualifier would mean it might be easier to capture some indirect topics that would be harder to add if it was the target level that was given. On the other hand, by using targets on all added statements, the data is added will have a stronger and cleaner connection.

Any thoughts @Daniel-Mietchen?

**Comment by Daniel-Mietchen** [comment]
Perhaps we should give it a try at all four levels of granularity (SDGs/ Goals/ Targets / Indicators). My hunch is that Indicators would be most useful in most cases, except when higher-level concepts are being discussed.

Another thing to consider is that the SDGs are currently meant to last just until 2030, so we may need something more general like "relates to sustainability proxy" or so, which could take values for all four levels of granularity of the current setup but also similar indicators that exist elsewhere or that come later.

**Comment by Ainali** [comment]
I am not sure what you mean by "try at all four levels". Do you mean several properties? Or that you would qualify by any of them? 

This was what I first imagined: 

`carbon tax (Q288401)` : `relates to sustainable development goal` : `Sustainable Development Goal 13 (Q53581236)`
> `applies to part (P518)` : `Target 13.2 of the Sustainable Development Goals (Q57590884)`

Do you mean that we should use either targets or indicators as qualifiers to the root, or something else? 

I am also unsure what would be the fourth level. Something "higher" than a specific goal?

**Comment by Ainali** [comment]
Well, If we allow for different types of values on the same property, each query will need a manual analysis in order to figure out what the results are. I'd rather go for a property with a strict value set. If it is the goals, targets, or indicators I am not sure of yet, but I think it should be only one of these types (and others possibly as qualifiers). This will make results from queries relatively straight forward to understand.

**Comment by Ainali** [comment]
Property proposal has been created: https://www.wikidata.org/wiki/Wikidata:Property_proposal/relates_to_sustainable_development_goal,_target_or_indicator

**Comment by Ainali** [comment]
The property has been created! :tada: 
https://www.wikidata.org/wiki/Property:P12933
